#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	foreground=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	background=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	black=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	lightgrey=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
	red=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	altred=$(xrdb -query | grep 'color9:'| awk '{print $NF}')
	green=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	yellow=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	blue=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	magenta=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	cyan=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	white=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations --------------------------------------------#

# If DisplayPort-2 connected, split workspaces to both monitors
if [ "$(xrandr | grep "DisplayPort-2 connected")" ]
then
    bspc monitor DVI-D-0 -d 1 2 3 4 5
    bspc monitor DisplayPort-2 -d 6 7 8 9 10
	# Reorder monitors
	bspc wm -O DVI-D-0 DisplayPort-2
else
    bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9 10
fi

# Used to make polybar maintain proper workspaces per monitor when going from 2
# to 1 monitor again.. This may include some monitor re-ordering issues
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true


bspc config border_width 2
bspc config window_gap 3
bspc config split_ratio 0.52

bspc config focused_border_color "$altred" 
bspc config normal_border_color "$background"
bspc config active_border_color "$lightgrey"
bspc config presel_feedback_color "$green"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

#  > office and docs
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

#  > Communication
declare -a comm=(Thunderbird Hexchat)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

#  > media
declare -a media=(Audacity Music MPlayer Lxmusic Inkscape Gimp-2.10 obs)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done

#  > settings
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

# special rules
declare -a floating=(Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

#bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager

# Lauch notification daemon
dunst \
-geom "300x70-5+25" -frame_width "1" -font "Ubuntu Regular 11" \
-lb "$background" -lf "$foreground" -lfr "$red" \
-nb "$background" -nf "$foreground" -nfr "$red" \
-cb "$background" -cf "$red" -cfr "$red" &

# Lauch xsettingsd daemon
xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash $HOME/.fehbg

# Start mpd
exec mpd &

# Network Menu
nm-applet &

# Monitor Setup
sh ~/.screenlayout/main.sh &

# Start bspwm scripts
bspcolors
bspbar
bspcomp &
#bspfloat &